[project]
name = "terminusgps-site"
description = "Terminus GPS website"
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.11"

authors = [
    { name = "Blake Nall", email = "blake@terminusgps.com" },
    { name = "Lili Noack", email = "lili@terminusgps.com" },
]


[tool.ruff]
exclude = [
    "node_modules",
    ".venv",
    "venv",
    "__pycache__",
]

target-version = "py311"

[tool.ruff.lint]
fixable = [ "ALL" ]
select = [ "E4", "E7", "E9", "F" ]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
