[project]
name = "terminusgps-site"
description = "Terminus GPS website"
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.11"

authors = [
    { name = "Blake Nall", email = "blake@terminusgps.com" },
    { name = "Lili Noack", email = "lili@terminusgps.com" },
]

[tool.ruff]
builtins = ["objects"]
target-version = "py312"
extend-exclude = ["migrations/*.py", "tests/*.py"]

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.lint]
logger-objects = ["terminusgps.logger"]
